# Generated by Django 5.1 on 2024-08-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='lien',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ImageField(default=1, upload_to='profile_pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='tel_mobile',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
