# Generated by Django 5.1 on 2024-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profil_lien_profil_photo_profil_tel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='lien',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tel_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
